### ISSUE TITLE
order_status_id missing when I open the order history and hit details. 

### ISSUE THREAD

**Issue by naneri** [multimerch/multimerch#100]
I get the following notices at the top of the page when I try to open the order details history: 

Notice: Undefined index: order_status_id in C:\xampp\htdocs\tura\vqmod\vqcache\vq2-catalog_controller_account_order.php on line 303
Notice: Undefined index: order_status_id in C:\xampp\htdocs\tura\vqmod\vqcache\vq2-catalog_controller_account_order.php on line 305
Notice: Undefined index: order_status_id in C:\xampp\htdocs\tura\vqmod\vqcache\vq2-catalog_controller_account_order.php on line 342

Here is the printscreen. 
![5b8af604b5ef22ddfafb5bab8716ede85d25abc027ed75ef52 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/5573469/10219082/c6b92f3a-685d-11e5-919f-cd813bf12c44.jpg)

**Comment by ffctcc** [comment]
Please make sure you're running the latest version of MultiMerch from GitHub and that you're selling a product that belongs to a vendor. MultiMerch doesn't support vendorless products at the moment.

**Comment by naneri** [comment]
@ffctcc thank you, removing vendorless products has solved my issue.

**Comment by cyberformed** [comment]
and what about own store products? have ever think of that. or we have to change multimerch core in catelog/catalog/filter.php code.

**Comment by ffctcc** [comment]
This is a work in progress.
