### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by ahmadsyamim** [multimerch/multimerch#103]
Im getting this error while creating new product on uploading image . Can anyone assists?
![capture](https://cloud.githubusercontent.com/assets/14102774/10361767/ddae72fc-6ddc-11e5-9f39-9dbe3caec736.PNG)

**Comment by ffctcc** [comment]
Form submission and file upload errors can be caused by a number of reasons. Please check your OpenCart error log in system/logs/error.txt for the exact error message.

**Comment by ahmadsyamim** [comment]
SOLVED : mbstring PHP extension not installed. After installed mbstring, solved and tested. Thank you ffctcc for replying. =)
