### ISSUE TITLE
problem in seller/account-product , products list won't load

### ISSUE THREAD

**Issue by hardjob** [multimerch/multimerch#105]
the issue is on this file account-product.php i have to replace it with file from older version to get it works 
 the products list won't load , it stays on loading state like that :
![loading](https://cloud.githubusercontent.com/assets/8091800/11454556/cdcf13be-9627-11e5-88b4-2ca13df5b6fb.png)

**Comment by ffctcc** [comment]
Please see the "Seller, seller group and product tables are empty" question and debug process at http://docs.multimerch.com/knowledge_base/topics/common-problems. What is the exact error message you're getting in console/logs?

**Comment by hardjob** [comment]
I got no error with the last account-product.php file from github
but with the older one i got this 
PHP Notice: Undefined index: p.date_created in catalog/controller/seller/account-product.php on line 118

**Comment by ffctcc** [comment]
Yes, this was a bug in the previous version of the file. We've fixed this in the current version.
