### ISSUE TITLE
error notice on filter while adding new product

### ISSUE THREAD

**Issue by kalpeshdesai20** [multimerch/multimerch#109]
Hi when I enable filter option for seller from admin
admin -> MM -> setting -> product form -> "include fields for product" , I got error while adding new product as attached file here and I go below error as you can see attached file.
 Notice: Undefined variable: product_filters in /home/shoppincent/public_html/catalog/view/theme/default/template/multiseller/account-product-form.tpl on line 545
find the attached file of screen shot.
![whilechecked filters](https://cloud.githubusercontent.com/assets/15693783/11789619/69349e86-a2bd-11e5-8f09-2f4720540997.PNG)
![whilechecked filtersfronterror](https://cloud.githubusercontent.com/assets/15693783/11789620/6953a6a0-a2bd-11e5-9604-ebd5ca659cd2.PNG)

**Comment by ffctcc** [comment]
This should be fixed in the latest GH version.

**Comment by kalpeshdesai20** [comment]
thank you Martin.
