### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Panfivan** [multimerch/multimerch#112]
Clean OpenCart 2.1.0.1 installation, vqmod 2.5.1. Trying to install MultiMerch 7.3.1 and get this error:
Notice: Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
Error No: 1171
CREATE TABLE `ms_attribute_attribute` ( `ms_attribute_id` int(11) DEFAULT NULL, `oc_attribute_id` int(11) DEFAULT NULL, PRIMARY KEY (`ms_attribute_id`, `oc_attribute_id`) ) DEFAULT CHARSET=utf8 in /home/www/prostoskachay.ru/system/library/db/mysqli.php on line 41Warning: Cannot modify header information - headers already sent by (output started at /home/www/prostoskachay.ru/admin/index.php:84) in /home/www/prostoskachay.ru/system/library/response.php on line 12.

Please help.

**Comment by ffctcc** [comment]
Looks like an issue with one particular version of MySQL. Replacing

`ms_attribute_id` int(11) DEFAULT NULL,
`oc_attribute_id` int(11) DEFAULT NULL,

with

`ms_attribute_id` int(11) NOT NULL,
`oc_attribute_id` int(11) NOT NULL,

in admin/model/multiseller/install.php should fix it.

**Comment by Panfivan** [comment]
Thank you, for your respond. It looks like the problem was with my hosting. Sorry about that. Today I installed OpenCart and MultiMerch without mistakes on another server.
But now I recieved another problem: if I go to Seller Dashboard->Statistics->tab By Product I get endless loading and OpenCart error.log has this:
2015-12-28 19:07:07 - PHP Notice:  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order o USING (order_id)
				LEFT JOIN ms_order_product_data
					USING(order_' at line 3<br />Error No: 1064<br />SELECT SQL_CALC_FOUND_ROWS  product_id, name, SUM(seller_net_amt) AS total_by_product, SUM(quantity) as sold
				FROM order_product
				JOIN order o USING (order_id)
				LEFT JOIN ms_order_product_data
					USING(order_id, product_id)
				WHERE	o.order_status_id	in	(5) AND seller_id =  1 GROUP BY product_id  HAVING 1 = 1  ORDER BY product_id ASC in 
/system/library/db/mysqli.php on line 41
2015-12-28 19:07:07 - PHP Notice:  Trying to get property of non-object in system/library/msstatistic.php on line 83
2015-12-28 19:07:07 - PHP Notice:  Trying to get property of non-object in /system/library/msstatistic.php on line 84
2015-12-28 19:07:07 - PHP Warning:  Invalid argument supplied for foreach() in /catalog/controller/seller/account-stats.php on line 168

I hope you can help me

**Comment by ffctcc** [comment]
Please replace

JOIN " . DB_PREFIX . "order o USING (order_id)

with

JOIN `" . DB_PREFIX . "order` o USING (order_id)

in system/library/msstatistic.php.

That will fix it.
