### ISSUE TITLE
MultiMerch Installation Error - ControllerMultisellerBase class not found

### ISSUE THREAD

**Issue by dilipsoni** [multimerch/multimerch#113]
I am unable to found this class when i am installing multimerch every time

MultiMerch Installation Error - ControllerMultisellerBase class not found

This usually means vQmod is missing or broken. Please make sure that:

1. You have installed the latest version of vQmod available at http://vqmod.com/
2. You have run vQmod installation script at http://localhost/shop/vqmod/install/ successfully (see Installing vQmod on OpenCart for more information)
3. Your vqmod/ and vqmod/vqcache/ folders are server-writable. Contact your hosting provider for more information
4. You have copied all MultiMerch files and folders from the upload/ folder to your OpenCart root

is there any solution for this??

**Comment by PXLTCH** [comment]
i also got the same error and in admin also i got this error
`Notice: Trying to get property of non-object in C:\xampp\htdocs\catalog\controller\common\header.php on line 5
Fatal error: Call to a member function getTotalProducts() on a non-object in C:\xampp\htdocs\catalog\controller\common\header.php on line 5`

**Comment by ffctcc** [comment]
Just like the error states, this means you have a missing or broken vQmod. MultiMerch will not work without vQmod so you need to make sure you have the latest version of vQmod for OpenCart (not standalone) installed from vqmod.com and functioning correctly.
