### ISSUE TITLE
Can't initialise $this->load->model('tool/image');

### ISSUE THREAD

**Issue by roro6969** [multimerch/multimerch#114]
Hi,
I want to get seller avatar in header.tpl, but when i use this code : 
`$this->load->model('tool/image');
$seller = $this->MsLoader->MsSeller->getSeller($this->customer->getId());`

I have this error Notice : Undefined property: Loader::$load, so how can i call the loader and MsLoader in template ?

Thanks,

Roro

**Comment by ffctcc** [comment]
You need to do it in the header.php controller (not template), then pass the avatar to the template in the $data array.
