### ISSUE TITLE
how to use without vqmod and ocmod ? manually core change.

### ISSUE THREAD

**Issue by PXLTCH** [multimerch/multimerch#118]
i want to use multimerch in my web site oc 2.1.0.1 and i have created database , 
I dont want to use any vqmod or ocmod , both will not work in my web site because i changed and updated all oc core system and i want to use only manualy code , any vqmod or ocmod file will not work in my web site because of code line and names change.vqmod search function will not find searched code to add or replace

i updated already all your .xml code to manualy by hand to my opencart core but still no work and error, can you help me ? i explainer here.

for example i changed all places where used like "" require_once(VQMod::modCheck(DIR_SYSTEM . 'library/msloader.php')); "" also but still have error.

in front end we have this error

Notice: Trying to get property of non-object in C:\xampp\htdocs\catalog\controller\common\header.php on line 5
Fatal error: Call to a member function getTotalProducts() on a non-object in C:\xampp\htdocs\catalog\controller\common\header.php on line 5

and in the back side we have this error
Notice: Undefined property: Loader::$load in C:\xampp\htdocs\admin\view\template\common\header.tpl on line 186
Fatal error: Call to a member function model() on a non-object in C:\xampp\htdocs\admin\view\template\common\header.tpl on line 186

**Comment by PXLTCH** [comment]
your customer support is weekness,  2 days past and still no answer

**Comment by osworx** [comment]
What do you expect??
Fiddeling around with no knowledge and now assuming that others will help you?
In what kind of world are you living?

**Comment by ffctcc** [comment]
Like I mentioned earlier and as explicitly specified in our FAQ, MultiMerch is not designed to be and will not work correctly and consistently when installed through manual modifications.

I'm afraid we can't really help you much if you're rewriting MultiMerch core systems to use them in a non-intended way. I assume your error is caused by a broken MultiMerch/OpenCart class loader mechanism.
