### ISSUE TITLE
Multimerch Paypal Adaptive Error!

### ISSUE THREAD

**Issue by edcabralc** [multimerch/multimerch#124]
Hi there,

I have set up paypal adaptive payment method, on my marketplace website.
I need that the buyer pay the items and the shipping cost that the seller has set. The store fee is 10% of the item cost.

My paypal account is verified and business one.
My app credentials is ok.

I have set up the paypal details on chained and the fee payer is secondary receiver.

When i check out the shopping cart, the system says:
"Configuration Error: Invalid Amount Distribution. Order ID: 57"
 Then, i change name the xml archive physical_multiseller_adaptive but the order not work

How fix the problem?

**Comment by ffctcc** [comment]
Please mail us at support@multimerch.com and provide your full debug and paypal.log files. Thank you.

**Comment by edcabralc** [comment]
Problem solved
