### ISSUE TITLE
MultiMerch feature requests

### ISSUE THREAD

**Issue by ffctcc** [multimerch/multimerch#18]
Feel free to submit your feature requests here. If you're a developer, you can use this list to see what features have potential to become a next MultiMerch addon!

**Comment by mikebees** [comment]
I think a map showing the sellers location using google maps would be good.

Also allow buyers to search for sellers in their local area using the map feature.

Social logins would be a great addition too

**Comment by MichaelEmx** [comment]
FILTERS
Guys, if you would like to get this extension we can buy it all together; write me (profile's email).

**Comment by mikebees** [comment]
what do u mean buy it together?

**Comment by jqtank** [comment]
Yea, what do you mean? 
I already paid for MM and it's still experiencing some bugs so I can't fully release my store. I'm hoping they will implement some of these features so I feel like it was money well spent.

**Comment by ffctcc** [comment]
Thanks for suggestions, guys, even though I don't post here we're monitoring this thread.

@jqtank: Which of the bugs are you experiencing exactly? Don't hesitate to create/bump additional issues or mail us at support@multimerch.com or mail me personally at martin@multimerch.com. if there's something that prevents you from opening your store.

**Comment by jqtank** [comment]
Hey Martin, I don't post my findings, since it's almost certain that someone has reported it or that MM Team will fix it in the following update. Last release 7.0.1.3b I experienced some frontend issues and errors but were fixed in 7.0.1.7 (Just installed yesterday). I haven't done full testing on my new update yet, but I know that you guys are on top of it. I'm hesitating release until it's more stable.

Any news on if/when these enhancements will be implemented or considered? :)

**Comment by ffctcc** [comment]
Now when OpenCart2 transition is completed for the most part we'll be turning to extra features. In fact, we've just set up a beta installation of a new platform to make discussing feature requests and other things easier (GitHub isn't the best platform for that).

Please check it out at community.multimerch.com (it should also have GitHub and Facebook login options) and see the Filters Feature discussion topic I've created. Really interested in what you think the filter creation/management process for sellers in MultiMerch should be and what options should sellers have when it comes to filters.

**Comment by sapnadhalor** [comment]
can we have an option to rate seller as well apart from the products.
one more request, a feature which gives users a forum like workplace to share their experience about products and owners would be great.
Hope to see these options in near future.

**Comment by py6etc** [comment]
Add possibility to use attributes which was created for all open cart products, not just for MultiMerch. Right now for MultiMerch products I is needed to create new attributes even they have the same names as open cart attributes

**Comment by ffctcc** [comment]
From now on, please use MultiMerch Forums as a better alternative to suggest and discuss new features: http://community.multimerch.com/c/development/feature-requests. Thank you.
