### ISSUE TITLE
Multimerch Shipping division by zero error

### ISSUE THREAD

**Issue by realsaiko** [multimerch/multimerch#31]
Using Multimerch Shipping bundle. If seller creates product with weight 0 and uses combined shipping, the client get division by zero error in checkout.
Error would be in /catalog/controller/checkout/multiseller_shipping_method.php line 446.

**Comment by ffctcc** [comment]
Fixed, shipping costs for zero-weight products will default to zero for combined shipping. The fix will be included in the next update.
