### ISSUE TITLE
MultiMerch Shipping double currency conversion problem

### ISSUE THREAD

**Issue by realsaiko** [multimerch/multimerch#32]
There is somewhere an error when calculating shipping cost in different currency. It makes double currency conversion. For example default shipping cost is 2 EUR (default currency). So there is no problem in checkout when buying in default currency (EUR). Then just changing currency to USD and going to checkout the shipping cost will become 3.06 USD. (Today's rate 1 EUR = 1.23730004 USD). So it goes like:
2 * 1.23730004 * 1.23730004 = 3.06
Same with Total calculation. The error exists in Fixes and Combined shipping.

**Comment by ffctcc** [comment]
This should be fixed in the latest Shipping update. If you encounter this again, please reopen this issue.
