### ISSUE TITLE
SignUp Fee in different currency

### ISSUE THREAD

**Issue by realsaiko** [multimerch/multimerch#34]
There is a problem when seller pays sign up fee in other currency than webshop paypal account currency. For example, webshop paypal default currency is in USD and seller pays sign up fee in EUR. Seller goes to paypal, pays the fee, get back to shop and he is asked to pay again, because no paymant was made.
This is because in PayPal answer you get `[payment_status] => Pending` and `[pending_reason] => multi_currency` . But the problem is that seller did pay and he asked to pay again.

Another problem is that seller selects currency in webshop USD, but sign up fee are made in default webshop currency - EUR. In database table oc_ms_payment the amount is in default currency, currency_id is for default currency and currency_code is selected currency by seller (but in payment the default currency is selected).

**Comment by ffctcc** [comment]
Currency conversions should be working fine with the latest versions of MultiMerch & Adaptive.
