### ISSUE TITLE
MultiMerch error in ModelTotalMsShipping

### ISSUE THREAD

**Issue by realsaiko** [multimerch/multimerch#35]
Got a situation:
Seller uses fixed shipping. Buyer puts product to the cart and we got:
`Undefined index: shipping_methods in <b>/var/www/vhosts/lithuanianmall.com/httpdocs/catalog/model/total/ms_shipping.php</b> on line <b>15</b>`

Line 5 is check 
`isset($this->session->data['shipping_methods']) || isset($this->session->data['seller_shipping_methods'])`

But on lines 14 and 18 there is no check if you really have this session data. It just uses it.

**Comment by ffctcc** [comment]
Fixed in the current version of MultiMerch.
