### ISSUE TITLE
Order Is Not Showing In Seller Dashboard

### ISSUE THREAD

**Issue by satyajit9830** [multimerch/multimerch#41]
Order Is Not Showing In Seller Dashboard After Order Is Placed. 
No Record In Inserting In Database Also.

**Comment by ffctcc** [comment]
One Page Registration isn't included with MM7 for OC2 yet. We're working on making it in a better way than it was in OC1 for better custom theme compatibility. It'll be included in one of the next updates. Meanwhile, seller profiles can be filled out through the standard user account.
