### ISSUE TITLE
PayPal Adaptive error with float numbers

### ISSUE THREAD

**Issue by realsaiko** [multimerch/multimerch#44]
Got a strange error in paypal.log:
2015-01-01 20:31:02 - Configuration Error: Invalid Amount Distribution. Order ID: 103 Order total: 31.73 Payable amount: 31.73

This error comes from PayPal adaptive extension:
if ($payableAmount > $total) {
	$this->_log->write("Configuration Error: Invalid Amount Distribution. Order ID: {$order_info['order_id']} Order total: {$total} Payable amount: {$payableAmount}");

I think the error could be with float number comparison.

**Comment by ffctcc** [comment]
Yes, this does look like an issues with conversion of floats. Checking it out along with the rest of currency-related issues.

**Comment by ffctcc** [comment]
Can you post specific steps to reproduce this? We couldn't do that testing Adaptive with different currencies.

If you can reproduce it, does adding an explicit (float) cast to both $payableAmount and $total in the conditional fix this?
