### ISSUE TITLE
Seller List and Product list not showing 

### ISSUE THREAD

**Issue by prashantweb** [multimerch/multimerch#46]
Something is really wrong with either Opencart Version 2.0.1.1 or Multimerch, i am using both latest version everything was fine. When i tried to assign a product to a seller which was listed by admin , seller list and product list stopped showing. I reinstalled MM , vqmod but nothing problem is still there. I can't understand the issue. After checking lots of files it seems like jSon datatables stopped working for some strange reason and table is not being generated although through PHP i can see all the data (array data which should be shown in jSon generated table). I have tried registering new seller from Admin panel and by front end nothing is solving my problem.

**Comment by ffctcc** [comment]
Please forward your error logs and admin credentials to support@multimerch.com so that we can check it out. Thank you!

**Comment by brajnep** [comment]
I am also facing the same issue. No product is being displayed in the sellers area.

**Comment by ffctcc** [comment]
Please update to the latest MM version available here on GitHub.

**Comment by jengkoil** [comment]
Hi, I have installed OC2.0.1.1 & installed latest MM v7.1 from github. My problem is I created new seller but not showing in seller list. I can login using new seller account & tried to add new product, also not showing product list under MM menu -> Products.. Please advise because I tested on your demo it's worked..

**Comment by ffctcc** [comment]
This is usually caused by JavaScript errors. Please check your JavaScript console and see if there are any JS errors. Those would prevent DataTables from showing up.

**Comment by jengkoil** [comment]
Thank you for reply, I have enabled firebug, error at 
admin/view/javascript/multimerch/datatables/lang/en.lng 404 Not Found, but I already check inside lang folder have en.lng
