### ISSUE TITLE
Rich text editor for sellers

### ISSUE THREAD

**Issue by esjulien18** [multimerch/multimerch#52]
I have the latest versions of opencart and when a sellers tries to add an html document to the rich text editor it doesn't display on the profile. It works on the back end. all other editor are working. It only the profile editor on the front end that won't work.

**Comment by ffctcc** [comment]
Please try applying this commit and let me know if it works: https://github.com/multimerch/multimerch/commit/113d41df6f724b987c6972abe63b286ea2ab72fb

**Comment by esjulien18** [comment]
Thanks that seems to solve my problem. But now when I add long document to the editor it says can not be over 1000 characters. Again this only happens on the profile pages for sellers. New products work fine with any size document. How can I increase this limit?

**Comment by esjulien18** [comment]
I found it. You can disregard my last remark. Thanks for the help.

**Comment by curiousPup** [comment]
being faced by the same problem, I applied these commits but it alas! it did not work for me. Can you please suggest some alternative.
thanks

**Comment by ffctcc** [comment]
What version of MM7 is this exactly? (can be found in system/library/msloader.php)

**Comment by curiousPup** [comment]
its 7.0.1.7
please help

**Comment by curiousPup** [comment]
its MM 7.0.1.7
It worked partially. I can apply text formatting and it is now working fine. But my project is almost crashed if I try to upload an image. The image is not uploaded, instead the specification tab stops working and specification data gets clubbed with description tab.
Its devastating. Please help

**Comment by ffctcc** [comment]
Please mail us a support request to support@multimerch.com with your OpenCart setup information and admin/ftp accesses. We haven't yet had anyone with such problems.

**Comment by curiousPup** [comment]
thank u very much but i managed to do it with the help of opencart's image manager. its working now. thanks anyway
