### ISSUE TITLE
Problem when adding Product with Multi Languages

### ISSUE THREAD

**Issue by blacklionxs** [multimerch/multimerch#54]
Hi,

I Have a Problem when i try to add product multimerch latest, when page of add product opened i find 3 "Name" case and 3 "Description" case , my opencart have 3 languages, 
i want when seller click on a language in the tab it give him the "name" and "description" of this language
![sans titre](https://cloud.githubusercontent.com/assets/10803075/6051848/0235cd0a-accc-11e4-9348-b2a2043edcb1.png)
![sans titrez](https://cloud.githubusercontent.com/assets/10803075/6051853/08a4a288-accc-11e4-8f28-a8c6a7f0f7bf.png)

uages

**Comment by ffctcc** [comment]
Please see this commit from yesterday that should fix it: https://github.com/multimerch/multimerch/commit/96e27c76d8958b38bbedf5c417cadb8d0cfe4759

**Comment by blacklionxs** [comment]
@ffctcc Thank you so Much , this fixed my problem :)
