### ISSUE TITLE
Not show order in seller dashboard

### ISSUE THREAD

**Issue by riyasck** [multimerch/multimerch#57]
Hi,
I just install multimerch.Adding product is working fine.But not shown seller orders in seller dashboards and deller order tab.

order shown main admin panel but shown seller  dashboard (using opencart 2 and multimerch 2-7.0.1.7)

**Comment by blacklionxs** [comment]
https://github.com/multimerch/multimerch/issues/53

**Comment by ffctcc** [comment]
Make sure that orders are completed as previous versions of MM don't show incomplete orders. if you need pending orders displayed, please update to MM 7.0.2 and check the "Display order statuses" in Misc settings.
