### ISSUE TITLE
make seller registration seperate

### ISSUE THREAD

**Issue by riyasck** [multimerch/multimerch#58]
How to make seller registration separate from  customer registration

**Comment by ffctcc** [comment]
The latest MM version introduces two-step simple seller registration that is completely separate from customer registration form.

**Comment by anuj1993** [comment]
could you please tell me the file name of seller registration where i'm add some field.
thanks for MM

**Comment by ffctcc** [comment]
For seller account fields, see our guide at http://multimerch.com/blog/creating-custom-seller-account-fields-multimerch/. For products, you'll need to modify account-product.php controller and account-product-form.tpl template.

**Comment by topazdecimal** [comment]
Please i can't seem to find seller login or sign up on my project, I have to sign up seller from the admin backend and can't see the seller's page

**Comment by ffctcc** [comment]
In this case you will need to follow our custom theme integration guide at
http://multimerch.com/docs/custom-theme-compatibility – check your vQmod
logs and adjust MultiMerch's product page xml file to match the code in
your theme's product page template.

**Comment by topazdecimal** [comment]
Thanks. This helped me to an extent. I can now see seller login/sign up. The issue now is that seller can't add products. The submit button does not respond. You can look up my installation at www.shopabuja.ng.

**Comment by ffctcc** [comment]
Please forward us your error logs and demo seller credentials to
support@multimerch.com so that we can take a look. This is usually caused
by JavaScript errors of different kinds so we need the details to debug
this.

**Comment by topazdecimal** [comment]
Hello Martin, I've sent a mail to the support email. Thanks

**Comment by ashishsharma275** [comment]
sir please tell me  my seller list is not show  on seller page but  i can login to email id and password ,also ican't add product with seller account . please hlep me

**Comment by ffctcc** [comment]
Please update your MM installation to the latest version available here on GitHub at http://github.com/multimerch/multimerch/. If it still doesn't work, forward your OpenCart's system/logs/error.txt log file to support@multimerch.com. Thanks.

**Comment by ashishsharma275** [comment]
sir problem not fix  please help me
PFA
