### ISSUE TITLE
Signup Seller with Fee 

### ISSUE THREAD

**Issue by mohmmadalabed** [multimerch/multimerch#6]
I need to set signup fee for every new seller
- Seller validation = No validation
- sellers group -> Signup fee / method = 50 - PayPal
- PayPal account is Turkish (country = Turkey)

now every things are okay and when new user want to be seller he will redirect to PayPal to pay 50 USD and finish this successfully
my problem is when the seller finish his pay, he should see his account is activated automatically ... but that doesn't happen with me
I have to go to back-office and make this seller as active seller manually, or I should go to my PayPal profile and make the encoding = UTF-8 and then it will be activated automatically.
do you think we can solve this issue from code , not from PayPal sitting.

(important notice : if your PayPal not Turkish,,, every things will work correctly)

**Comment by ffctcc** [comment]
Currency conversions should be working fine with the latest versions of MultiMerch & Adaptive.
