### ISSUE TITLE
Bug in Account Order Shipping

### ISSUE THREAD

**Issue by SadikBhimani** [multimerch/multimerch#62]
In public function jxRenderMarkShippedDialog() for the shipping addon the returns need to be updated to OC 2 methods.

So instead of 

list($this->template, $this->children) = $this->MsLoader->MsHelper->loadTemplate('dialog-markshipped');
return $this->response->setOutput($this->render());

Needs to be

list($template, $children) = $this->MsLoader->MsHelper->loadTemplate('dialog-markshipped');
$this->response->setOutput($this->load->view($template, array_merge($this->data, $children)));

Same for jxRenderBuyerAddressDialog method.

**Comment by ffctcc** [comment]
Both are removed from the latest development version as there's a new order status system in MultiMerch Core. From now on orders are marked as shipped by changing order status in the "view order" page, the same page also displays buyer addresses and other information.

**Comment by SadikBhimani** [comment]
Sounds good Martin. Would it be wise to update to the latest versions from GitHub?

**Comment by ffctcc** [comment]
You can definitely update MM Core from GitHub. As to Shipping - we don't yet have it on GitHub, but we'll publish a new update to the customers shortly.
