### ISSUE TITLE
Paypal Adaptive Payments Error due to float comparison

### ISSUE THREAD

**Issue by SadikBhimani** [multimerch/multimerch#63]
Hi

In the paypal adaptive payments addon in the file ms_pp_adaptive.php in the send() method, you have the if condition.

if ($payableAmount > $total)

However I had a specific case when payable amount was a float (370.00) and total was an integer. (370)

This meant even though the condition should have evaluated to false it evaluated to true generating the error "Configuration Error: Invalid Amount Distribution..."

I fixed this by changing the if condition to comparison by the ellipsis method

if (abs($payableAmount-$total) > 0.001)

**Comment by ffctcc** [comment]
I'd suggest converting both to float with "decimal_place" decimal places via (float) or round() before the comparison. We'll probably implement one of those to fix this issue.
