### ISSUE TITLE
no warning when seller buys his own product

### ISSUE THREAD

**Issue by curiousPup** [multimerch/multimerch#64]
there should be an error or warning message when a seller tries to add a product to his cart which is created by him.
please guide me which files should i change to achieve the above stated scenario

**Comment by ffctcc** [comment]
You would need to modify the following files:

cart controller: catalog/controller/checkout/cart.php
product template: template/product/product.tpl
other templates that list products and have the "add to cart" button (bestseller.tpl,featured.tpl,latest.tpl,wishlist.tpl,search.tpl)

We have this partially implemented in our addtocart xml file under vqmod/xml/ and in the ms-common.js javascript file, but this hasn't yet been ported from OC1.
