### ISSUE TITLE
seller registration error and add new product error  

### ISSUE THREAD

**Issue by anuj1993** [multimerch/multimerch#65]
when i register as new seller on my localhost or your demo site its get error that "Error occured when submitting the form. Please contact the store owner for more information." and Next Step Not Continue.
And 'Add Cart Button' Not Working Properly For that Seller upload Product

 Product.
![register_issue](https://cloud.githubusercontent.com/assets/11503541/6841876/d685c4c8-d3b6-11e4-9ba4-2a0a934c9999.JPG)
![new_product_error](https://cloud.githubusercontent.com/assets/11503541/6841928/869ab4ea-d3b7-11e4-8e9a-cc5c90a6d59e.JPG)

And Please Give Me suggestion that how I remove Some Fields In Seller Registration Form.
And Lots Of Thanks For Making MULTIMERCH Core.

**Comment by curiousPup** [comment]
i had the same problem and it happened because of the code that sends an email after you register as a seller.
try again after putting correct values in mail settings in System > Settings

**Comment by anuj1993** [comment]
Thank You For Replay And All Problem "SOLVED".  i'm fan of you and Your Coding.
Could you please help how i remove some field In seller register form..
thanks in advance

**Comment by curiousPup** [comment]
a seller can not add his own product to cart

**Comment by anuj1993** [comment]
Thanks for solution.
Could you please help me to remove some field from registration form via vqmod.
Thanks in advance

**Comment by ffctcc** [comment]
You would need to make changes to the following files: register-seller.tpl template (remove the field itself) and account/register-seller.php controller (remove the validation for the field). That's it!

**Comment by anuj1993** [comment]
Thanks for last replay
Now I am add related product field in multimerch add new product page where seller add related product or similar product.
Thanks in advance

**Comment by pawanchauhan05** [comment]
can you please give proper mail configuration to remove this error....

**Comment by Servelatin** [comment]
The same error.. mail settings are normal.
In logs: PHP Warning:  Invalid argument supplied for foreach() in /home/s20023/public_html/mysite.ru/system/library/mail.php on line 22

There are:
![2015-04-19 22_01_43-](https://cloud.githubusercontent.com/assets/12141992/7355233/9c3850d0-ed31-11e4-9ead-54a3a8222ae4.png)
public function __construct($config = array()) {
		foreach ($config as $key => $value) {
			$this->$key = $value;
		}

**Comment by ffctcc** [comment]
Please try replacing $mail = new Mail($this->config->get('config_mail'));
with $mail = new Mail(); in system/library/msseller.php and let me know if
it works.

**Comment by Servelatin** [comment]
Thanks for reply.
There no such code in the file =(

**Comment by ffctcc** [comment]
Sorry, please try msmail.php instead.

**Comment by Servelatin** [comment]
Yeah! Thanks=) solved!

**Comment by mikened** [comment]
halo i have the same problem i try evryting bad not work

![image](https://cloud.githubusercontent.com/assets/12776231/8020228/787b8784-0c71-11e5-82bf-c0a73c733f3a.png)

**Comment by ffctcc** [comment]
Please update to the latest version of MM available here on GitHub at http://github.com/multimerch/multimerch/. This is fixed in the development version. If it still doesn't work, please forward your OpenCart's error.txt log to support@multimerch.com.

**Comment by mikened** [comment]
thank you very mach its work bad i have the next problem the text in the description not good

![image](https://cloud.githubusercontent.com/assets/12776231/8032735/bb412ea8-0dd8-11e5-8ff4-4d28fa79d246.png)

**Comment by ffctcc** [comment]
This is OpenCart's default behavior that isn't related to MultImerch. Under normal circumstances you have spaces in your descriptions which will make it wrap correctly. If you need the descriptions to consist of a single word, see this thread: http://stackoverflow.com/questions/3949762/how-to-wrap-text-using-css

**Comment by mikened** [comment]
oke thank you for you hulp ;)

**Comment by bimalesh2007** [comment]
I have installed opencart 2.0 and latest multimerch extension on godaddy server. I am getting this error:     Error occured when submitting the form. Please contact the store owner for more information.. Would you please help me to resolve the issue.

**Comment by Pooja123455** [comment]
"Error occured when submitting the form. Please contact the store owner for more information." while registering seller in server 
The reason behind this was, in server "mbstring" was not enabled in PHP extension. You can contact your web hosting for support.
Hope it may help you.
