### ISSUE TITLE
Opencart Override Engine

### ISSUE THREAD

**Issue by satyajit9830** [multimerch/multimerch#66]
I have installed opencart-2-0-1-0-override-engine-6-4-5 for my theme. When trying to access any front end page of seller like http://www.sevakart.com/index.php?route=seller/account-profile , its showing error. "Fatal error: Uncaught exception 'ReflectionException' with message 'Class ControllerSellerAccount-profile does not exist "

Can you help me please

**Comment by ffctcc** [comment]
You need "vQmod for OpenCart" from vqmod.com, not the Override Engine. Please see our installation guide for this.

**Comment by satyajit9830** [comment]
I have managed to figure out this. its not taking the dash (-) as class/function name should not contain dash. its taking underscore. 
Any way to hack it? means my theme need  Override Engine to work, and i have installed vQmod also. but the url is creating problem

**Comment by ffctcc** [comment]
What theme is this? You could try contacting them to see if they have a solution (as this doesn't happen with clean OC+vQmod/OCMOD). Alternatively, you could try renaming the files and removing the dashes, but this is kind of a dirty hack. Strange that Override Engine changes OC's standard behavior of loading models/controllers, I'd expect it to do it the default way.

**Comment by satyajit9830** [comment]
m using http://themeforest.net/item/eclipse-responsive-multipurpose-opencart-theme/10023133

**Comment by satyajit9830** [comment]
I have now new theme. Its useing vqmod.
Seller info is not showing product page. changed pathReplaces file. also uploaded the file in custom theme.

**Comment by ffctcc** [comment]
Have you checked our custom theme guide at http://multimerch.com/docs/custom-theme-compatibility yet? It describes what you need to do in detail if some parts of MM don't work with your theme out of the box.

**Comment by satyajit9830** [comment]
Yes checked, but not able to fix it.
If i provide u the ftp details, would u able to fix this for me? Please help me to fix it

**Comment by satyajit9830** [comment]
r u there ?

**Comment by ffctcc** [comment]
While we don't offer free custom theme integration services, feel free to mail us at support@multimerch.com with your complete details and we'll see if we can help you.

**Comment by bhargav77** [comment]
Hello #satyajit9830   i need to http://themeforest.net/item/eclipse-responsive-multipurpose-opencart-theme/10023133 for start my business. So, Are you interested bro for help me?

**Comment by anuragmittal10** [comment]
@satyajit9830 Dear Satyajit i am also using the same theme and getting same error in multimerchant. Can you please help me to resolve this. I have wasted so much of time. Please help buddy.
