### ISSUE TITLE
Error occured when submitting the form. Please contact the store owner for more information

### ISSUE THREAD

**Issue by abdallahpro** [multimerch/multimerch#74]
Hi
add new product , i see error
Error occured when submitting the form. Please contact the store owner for more information.

and error log opencart
PHP Warning:  Invalid argument supplied for foreach() in system/library/mail.php on line 22

my mail settings in opencart (Smtp) and working fine

and download latest version opencart and multimerch
whats the problem?

**Comment by ffctcc** [comment]
Please mail us your OpenCart log and mail configuration to support@multimerch.com. This is OpenCart's own error, not MultiMerch one.

**Comment by DaisyOne** [comment]
Hi, @abdallahpro .Have you solved this problem. I meet the same problem.

**Comment by ffctcc** [comment]
Please upgrade MultiMerch and OpenCart to the latest versions available. This has been fixed. If you're still experiencing issues, please mail us at support@multimerch.com.

**Comment by DaisyOne** [comment]
Thanks for your help. @ffctcc

**Comment by bimalesh2007** [comment]
I have installed opencart 2.0 and latest multimerch extension on godaddy server. I am getting this error: Error occured when submitting the form. Please contact the store owner for more information.. Would you please help me to resolve the issue.

**Comment by MuhamedAuda** [comment]
Hello.
If you set STMP as Mail protocol in opencart setting and not work well it will cause that problem.
I took a long time to dicover that so I revert back to set Mail Protocol: Mail ,
that's all ...thanks
