### ISSUE TITLE
New Product Form Cant Working 

### ISSUE THREAD

**Issue by Ersonusaini** [multimerch/multimerch#75]
Currently i'm Using Opencart v 2.0.2.0 and Theme Journal 2.12 

Multimerch Properly install 
![error](https://cloud.githubusercontent.com/assets/6860971/7388256/6fa5236c-ee81-11e4-8793-37023d88b864.png)
 
also layout not working as journal 2 layout using 
![image](https://cloud.githubusercontent.com/assets/6860971/7388282/8ec73b5e-ee81-11e4-921d-dbf0e9894724.png)

please help as soon 

Email : contact@ersonusaini.com

**Comment by ffctcc** [comment]
The latest versions of MultiMerch & Journal should be working fine with the current compatibility package.
