### ISSUE TITLE
Seller New Product Uploading issue

### ISSUE THREAD

**Issue by Ersonusaini** [multimerch/multimerch#77]
Seller Cant upload new product  bcuz new product form properly not lot in opencart 2.0.2.0 
with journal 2.12 

![error](https://cloud.githubusercontent.com/assets/6860971/7388505/564c9f2e-ee83-11e4-857e-ae5b3f5b1efe.png)

as soon reply me admin

**Comment by ffctcc** [comment]
The latest versions of MultiMerch & Journal should be working fine with the current compatibility package.
