### ISSUE TITLE
Product quantity doesn't work with product options 

### ISSUE THREAD

**Issue by mohmmadalabed** [multimerch/multimerch#80]
Hi, 
i just noticed, maybe it is not issue or i missed some thing ,,,, i will explain you 

1- I set the quantity to be 3

![first](https://cloud.githubusercontent.com/assets/7547061/7748227/410a6eda-ffcb-11e4-9cec-dc58a9110902.PNG)

2- then go to options and add two options with their quantities, 
red = 1
white = 4
then i saved this values ...
here is my first issue .. how it can save with 4 red and 1 white if the total quantity of this product is 3

![second](https://cloud.githubusercontent.com/assets/7547061/7748319/18856b30-ffcc-11e4-85b5-81b751f94b1d.PNG)

3- then some user go to buy this product and he ordered 3 product with red color  
Second issue is ...the user must not be able to order 3 red products because,, I set the quantity of red to be only 1

![third](https://cloud.githubusercontent.com/assets/7547061/7748339/4d55542e-ffcc-11e4-8675-0a8cc6ec89c9.PNG)

![fourth](https://cloud.githubusercontent.com/assets/7547061/7748345/53a1e414-ffcc-11e4-86b0-ab369b2ab3a2.PNG)

**Comment by ffctcc** [comment]
Hi,

OpenCart should not allow the customer to purchase more products of any kind (option) than the total quantity. This works in the same way in OpenCart – we simply fill out OpenCart's database field with the data, it then processes them by itself. If you create a product through OpenCart admin, it will work in the same way. Have you tried completing the order?

**Comment by mohmmadalabed** [comment]
Thanks for replay:
As you said "OpenCart should not allow the customer to purchase more products of any kind (option) than the total quantity. "

This is not my problem 
My problem is ... why the user can order 3 product with red color,, where my store has only 1 product with red color.

**Comment by ffctcc** [comment]
So, did you complete the order and it worked? Also, have you tried creating
the same product configuration through OpenCart?

I'm asking this because MultiMerch merely uses OpenCart's product system
for managing products and product options. If the same happens with
products created via OpenCart admin, then it's a bug in OpenCart, not
MultiMerch. If it doesn't, though, then it may be something on our side and
I will need more details and debugging information. If it's an OpenCart
bug, there's not much we can do apart from reporting it to the OpenCart
team.

**Comment by mohmmadalabed** [comment]
Ammm, now i can understand very well
I will try and let you know the results
thanks for replay

**Comment by mohmmadalabed** [comment]
hi,
i tried with regular product in opencart  as you told me 
opencart does not allow to order products more than the option quantity 

so that means the problem from MultiMerch

example:
product name:  test pro for options
Quantity: 5
Minimum Quantity:
Out Of Stock Status:  In Stock

![openc](https://cloud.githubusercontent.com/assets/7547061/7793458/ce4ed4b2-02c7-11e5-8d0d-ed20384167ac.PNG)

**Comment by ffctcc** [comment]
Thank you, we will investigate this further.

**Comment by ffctcc** [comment]
This should be fixed in the current version of MultiMerch.
