### ISSUE TITLE
Cannot redeclare ControllerCommonHeader::getCarriers()

### ISSUE THREAD

**Issue by rajat1366** [multimerch/multimerch#81]
Fatal error: Cannot redeclare ControllerCommonHeader::getCarriers() in  vqmod\vqcache\vq2-catalog_controller_common_header.php on line 246

and the website is stopped

**Comment by ffctcc** [comment]
MultiMerch doesn't have a function called getCarriers(). This means this is either coming from OpenCart Core or from a third party extension. Please make sure you only use extensions that are verified to work with your version of OpenCart.

**Comment by rajat1366** [comment]
i think the problem is with integration with the theme. Can you help with the integration?  We want to go for the complete multimerch package but want to make sure it will work with our current theme and extension.

**Comment by rajat1366** [comment]
i am currently using pavotheme megashop

**Comment by ffctcc** [comment]
First, please see our custom theme guide at http://multimerch.com/docs/custom-theme-compatibility. Getting through this should fix most of issues. The error with carriers, though, seems to come from somewhere else, as we haven't encountered this yet, even with megashop. I'd suggest you contact them first and see if they have a solution for this. This doesn't seem to be MultiMerch-related.
