### ISSUE TITLE
PARSE ERROR in code

### ISSUE THREAD

**Issue by rajat1366** [multimerch/multimerch#82]
Parse error: syntax error, unexpected '<' in \vqmod\vqcache\vq2-catalog_view_theme_megashop_template_common_header.tpl on line 22

**Comment by ffctcc** [comment]
This is probably related to the other thread you submitted. Please make sure you only use extensions that are verified to work with your version of OpenCart. If you encounter MultiMerch-specific issues, please file a support request to support@multimerch.com along with your error logs and access to your server.
