### ISSUE TITLE
Question: install on shared hosting possible ? 

### ISSUE THREAD

**Issue by markizk** [multimerch/multimerch#85]
Hi, 

I want to install that on my server (I hosted one by a hosting provider) and now I have the problem that the vqmod would not install aoutomaticly. So I want to do it manually but I cant find the codelines to replace. 

Please help me :) 
If you want i can send you FTP informations by mail thanks
yours manuel

**Comment by ffctcc** [comment]
You need to make the index.php and admin/index.php files writable first (simply adjust the file permissions, you can do it even on a shared hosting). If you still want to do it manually, please see vQmod's wiki: https://github.com/vqmod/vqmod/wiki/
