### ISSUE TITLE
Multimerch and WampServer

### ISSUE THREAD

**Issue by ateliersimon** [multimerch/multimerch#87]
Hi everyone,
I set up a website using OpenCart on my computer, through WampServer, and I decided to install Multimerch (free edition) in order to test it. But there are problems with installation. I'm unable to understand how it works. (vQmod is installed)
I download and unzip files, then I put the "upload" file (from multimerchmarketplace) in my OpenCart installation directory. Then, when I go to Admin-Extension-Modules : nothing appeared. So, it's impossible to install Multimerch.
Have an idea ?
Regards,
Simon

**Comment by ffctcc** [comment]
You need to upload everything inside the upload folder, not the folder itself. Simply copy all folders inside upload/ and paste them into your installation root.

**Comment by ateliersimon** [comment]
Hi,
It works perfectly fine now. Thank you for your help.
Have a nice day !
Simon
