### ISSUE TITLE
Unable to change Order Status

### ISSUE THREAD

**Issue by ravdeepsingh22** [multimerch/multimerch#88]
There is a bug in multi merch 
Installed it on latest version of opencart
A seller is Unable to  change the order status or add history to order status.
Please fix this bug as soon as possible 
Please Please Help 
Thanks 
Ravdeep

**Comment by ffctcc** [comment]
Please make sure you are using the latest version of MultiMerch from GitHub. If the error persists, please mail us your error logs and setup information to support@multimerch.com.
