### ISSUE TITLE
Error occured when submitting the form. Please contact the store owner for more information.

### ISSUE THREAD

**Issue by DaisyOne** [multimerch/multimerch#89]
When I create a new product,it gets error that "Error occured when submitting the form. Please contact the store owner for more information." and Next Step Not Continue.
But I can see the new created product on my website and the admin/ Catalog/Products.
At the same time,I can't send any emails or notify customer.I have seen many sulutions for many days,and i have tried many ways,but it did not work.I don't know what is the problem.
Any replies may be useful.Thanks you in advance!
![new](https://cloud.githubusercontent.com/assets/13131511/8565154/691cc492-2585-11e5-810f-a264c15ceb6a.jpg)
![smtp](https://cloud.githubusercontent.com/assets/13131511/8565158/73a355ca-2585-11e5-8876-782381d71486.jpg)
![error](https://cloud.githubusercontent.com/assets/13131511/8565166/95e97ce0-2585-11e5-83ae-a677e7350d9d.jpg)

**Comment by ffctcc** [comment]
The error messages indicate your mailserver is not configured correctly. Please double check that your mailserver is up and running and that your SMTP configuration matches your server configuration.

**Comment by DaisyOne** [comment]
Thanks you very much. @ffctcc  The SMTP Hostname is correct,and its password is right.The problem is not solved. It has annoyed me a lot of days,and I have tried lots of solutions,but it didn't work.
![Uploading new.jpg…]()
![Uploading error log.jpg…]()
![Uploading ini.jpg…]()
![Uploading settings.jpg…]()

**Comment by ffctcc** [comment]
There'e one more error related to OC 2.0.2.0 changes. Please try updating your MultiMerch mail class file (system/library/msmail.php) to the latest version from GitHub and let me know if it works: https://github.com/multimerch/multimerch/tree/master/upload/system/library/msmail.php

**Comment by DaisyOne** [comment]
Thanks for your help. @ffctcc . I replaced the msmail.php,but I got the same  warning as before.Are there any errors for my settngs,I am no sure whether  my settings and php.ini are right.

**Comment by ffctcc** [comment]
Are you getting the same exact error in your error log or is it something different this time? The notification will be the same for any server-side error, so we need to know the exact error message from the log.

**Comment by DaisyOne** [comment]
I get the same warning,maybe there is something wrong with may settings and php.ini,but i can find it.

**Comment by ffctcc** [comment]
This isn't related to php.ini. Please mail us your admin-area and FTP credentials to support@multimerch.com so that we can debug this.
