### ISSUE TITLE
No Email To seller When an order is placed 

### ISSUE THREAD

**Issue by ravdeepsingh22** [multimerch/multimerch#90]
No Email To seller When an order is placed 
Seller is not receiving any email When an order is made or its status is changed

Please Help

**Comment by ffctcc** [comment]
First, make sure your orders are Completed or in one of the "fund order statuses". Second, if it still doesn't work, make sure your mail configuration in OpenCart is correct and that your mailserver working.

**Comment by ravdeepsingh22** [comment]
My mail server is working perfectly fine 
but seller is not getting an email 
Can you please send a mail automatically if the order is placed through Cash On Delivery 
It Will be very helpful
