### ISSUE TITLE
Multimerch and Journal

### ISSUE THREAD

**Issue by ateliersimon** [multimerch/multimerch#91]
Hi,
I'm installing Multimerch with Journal2 but I don't understand one step : "Unpack the archive, rename/copy the default template folder to your theme’s folder name and upload the contents of the multimerch_marketplace/upload/ folder from the archive to your server. " I'm not sure If I understand well. Is it "model" folder in "catalog" folder that I need to rename "journal2" and copy to my server; before copy the other files to my server ?

**Comment by ateliersimon** [comment]
Finally, I found the folder. Then, I follow the instructions step by step. But I got a serious problem when I install Multimerch. I don't know what it mean. Thanks in advance !

![image](https://cloud.githubusercontent.com/assets/12834916/8653851/252fa924-2987-11e5-9043-291f9f7580df.jpg)

**Comment by DaisyOne** [comment]
Your Multimerch didn't install in the right way.You can try thisway. http://multimerch.com/docs/installation/
I got the same peoblem,after using ftp to upload the files, and it worked.Hope it can help you.Good luck.
