### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by as-miller** [multimerch/multimerch#92]
I followed the instructions that were provided here to another user:

"You need to upload everything inside the upload folder, not the folder itself. Simply copy all folders inside upload/ and paste them into your installation root."

I have done a clean install of opencart, made sure VqMod is installed and have downloaded and have the 5 folders from the multimerch upload folder. I'm setting the multimerch core up locally using MAMP on Windows to test it out. Inside my MAMP root (htdocs) I have the opencart folder with the opencart folders/files. I've tried numerous ways to install multimerch with no luck so far. Where exactly do I place the 5 multimerch folders from the upload folder to install multimerch and have it available in opencart admin modules?

Would really appreciate any help

**Comment by ateliersimon** [comment]
You have to copy/paste the Multimerch files inside the Opencart installation folder

**Comment by ffctcc** [comment]
Exactly. You need to copy everything inside your upload/ folder into your OpenCart installation folder (the one that contains the index.php & config.php files and the rest of OpenCart folders).

**Comment by as-miller** [comment]
Thanks guys. Looks like I was placing the folders in the right place, though Multimerch still isn't showing up as being installed. Any ideas what else I might be doing wrong?

Thanks again

**Comment by as-miller** [comment]
Now that I think about it, I haven't simply copied the folders from the Multimerch upload folder into the OpenCart installation because a couple of the folders inside the Multimerch upload folder match those inside the OpenCart installation folder? Wouldn't these Multimerch folders just overwrite the OpenCart ones if I copy them there?

**Comment by ffctcc** [comment]
Most file managers and FTP clients will not overwrite the folders, but rather merge their contents. This is what you need. If you're using a non-standard application to do this, I'd suggest you make sure it merges the folders and not overwrites them, though.
