### ISSUE TITLE
Cannot redeclare Reloader

### ISSUE THREAD

**Issue by ateliersimon** [multimerch/multimerch#93]
![image](https://cloud.githubusercontent.com/assets/12834916/8670768/e4653d66-2a1f-11e5-9e27-5b8d21a4a578.jpg)

Hi,
I got a problem when I want to install Multimerch and Journal2. I install OpenCart, then vQmod, then Journal2. Then I upload Multimerch files. But when I want to go to "modules" to install Multimerch, this is what I get. 
Regards,
Simon

**Comment by ffctcc** [comment]
In this case, install the J2 integration pack first (the last step at http://multimerch.com/blog/opencart-journal2-multimerch/) or remove the vqmod/xml/multimerch_core_oc2_loader_magic.xml file. That should do it!

**Comment by ateliersimon** [comment]
It works well now. Thank you ! Have a nice day
