### ISSUE TITLE
please help with email to seller

### ISSUE THREAD

**Issue by ravdeepsingh22** [multimerch/multimerch#94]
My mail server is working perfectly fine 
but seller is not getting an email 
Can you please send a mail automatically if the order is placed through Cash On Delivery 
It Will be very helpful

**Comment by ffctcc** [comment]
Please make sure your COD module sets the order to Completed instead of Pending. MultiMerch doesn't send out "new order" mails for incomplete orders. Alternatively you can adjust MM's "Fund order statuses" setting and add Pending to it if it matches your workflow.

**Comment by OnRouteDev** [comment]
Just wanted to add/ask - is there anyway to pull the comments that a buyer may add at the end of checkout into the email sent to the seller?

**Comment by ffctcc** [comment]
This will be implemented in the next update.
