### ISSUE TITLE
Error occured when submitting the form. Please contact the store owner for more information.

### ISSUE THREAD

**Issue by cuiyan** [multimerch/multimerch#96]
when I  register seller account, first step，I click continue ,it  tell  me this。
![mall](https://cloud.githubusercontent.com/assets/8078373/9083000/61d0183a-3b9a-11e5-9cd1-e8a3ca45edc9.png)
I use 
opencart：2.0.3.1  and the lasted  multimerch
the project desployed aliyun ecs。
but I test it in my local pc with windows is ok。what shoul I do。

**Comment by cuiyan** [comment]
![mall_1](https://cloud.githubusercontent.com/assets/8078373/9083139/1bc76068-3b9b-11e5-942d-f6b4614ca81c.png)

**Comment by ffctcc** [comment]
Please check your server's error log file. The message indicates there's been an Internal Server Error 500. The cause for those errors is usually logged to your server's main error log.

**Comment by ashiton** [comment]
![error](https://cloud.githubusercontent.com/assets/13389455/12703519/c4744d1e-c86a-11e5-8129-66b6513c857e.png)
This error has arrived after I updated Multimerch to it's latest version from GitHub.
I use opencart 2.1.0.1 
What should I do

**Comment by ffctcc** [comment]
If you are having this issue with the latest versions of MultiMerch, check our Admin > MultiMerch > Debug output and see our entry about form submission errors at https://multimerch.com/docs/common-problems/.
