### ISSUE TITLE
Update order history does not work

### ISSUE THREAD

**Issue by rk1664** [multimerch/multimerch#98]
Updating the order history from Seller Dashboard->Your Orders does not work. Changing a pending order to another status and clicking on Add History reloads the page with the status still showing as pending. Nothing is added to the history list.

It is possible to update the order from the the Orders section in the Admin backend, and the staus is reflected in the seller's frontend, but no entry is added in the history list in the seller's front end.

Using Opencart 2.0.3.6 and Multimerch 7.1.2

Backend:
![capture](https://cloud.githubusercontent.com/assets/4700084/9416177/a9353c16-4809-11e5-9fae-54bb6ec6ecf5.PNG)

Seller frontend
![capture2](https://cloud.githubusercontent.com/assets/4700084/9416180/ac53532e-4809-11e5-827a-fd8e12e15c95.PNG)

**Comment by ffctcc** [comment]
This should have been fixed in the latest GitHub version of MultiMerch. Please try updating to the version that's available here on GH.

If it still doesn't work please mail us at support@multimerch.com along with your FTP and admin-area accesses as we'll need to debug this.
